services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./:/usr/app
  postgres:
    container_name: db
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:7.4.2-alpine
    ulimits:
      memlock: -1
      nofile:
        soft: 65536
        hard: 65536
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', '$REDIS_PASSWORD', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
