name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --target production \
            -t tauras-backend:latest \
            --load \
            .

      - name: Save Docker image to tar
        run: docker save tauras-backend:latest -o tauras-backend.tar

      - name: Set permissions on tar file
        run: chmod 644 tauras-backend.tar

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauras-backend-tar
          path: tauras-backend.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Docker image tar artifact
        uses: actions/download-artifact@v4
        with:
          name: tauras-backend-tar

      - name: Check Docker image tar file
        run: ls -l tauras-backend.tar

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'tauras-backend.tar'
          target: '~/app/'

      - name: Load and run Docker image on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/app
            ls -l tauras-backend.tar
            docker load -i tauras-backend.tar
            docker stop tauras-backend || true
            docker rm tauras-backend || true
            docker run -d --name tauras-backend -p 80:80 -v /usr/app/logs:/app/logs --restart unless-stopped tauras-backend:latest
